# Generado por matugen — NO EDITAR MANUALMENTE
$hl_text      = #f1dfd9
$hl_fg        = #f1dfd9
$hl_fg_dim    = #d8c2ba
$hl_outer     = a08d86
$hl_inner     = 271e1a
$hl_font      = f1dfd9
$hl_check     = ffb597
$hl_fail      = ffb4ab
