preload = /home/david/Pictures/Wallpapers/a_white_light_pole_with_a_jet_trail_in_the_sky.jpg
wallpaper = DP-2, /home/david/Pictures/Wallpapers/a_white_light_pole_with_a_jet_trail_in_the_sky.jpg
wallpaper = HDMI-A-1, /home/david/Pictures/Wallpapers/a_white_light_pole_with_a_jet_trail_in_the_sky.jpg
splash = false
