source = ~/.config/hypr/hyprlock-colors.conf

general {
    disable_loading_bar = false
    hide_cursor         = true
    grace               = 0
    no_fade_in          = false
}

background {
    monitor    =
    path       = /usr/share/wallpapers/EndeavourOS/contents/images/3840x2160.png
    blur_passes = 2
    blur_size   = 4
    brightness  = 0.5
    vibrancy    = 0.17
}

label {
    monitor      =
    text         = cmd[update:1000] echo " $(date +"%H:%M")"
    color        = $hl_text
    font_size    = 64
    font_family  = JetBrainsMono Nerd Font
    position     = 0, 80
    halign       = center
    valign       = center
}

label {
    monitor     =
    text        = $USER
    color       = $hl_fg_dim
    font_size   = 18
    font_family = JetBrainsMono Nerd Font
    position    = 0, -110
    halign      = center
    valign      = center
}

input-field {
    monitor          =
    size             = 300, 50
    outline_thickness = 3
    dots_size        = 0.3
    dots_spacing     = 0.15
    dots_center      = true
    outer_color      = rgb($hl_outer)
    inner_color      = rgb($hl_inner)
    font_color       = rgb($hl_font)
    fade_on_empty    = true
    placeholder_text = <i>Contraseña...</i>
    rounding         = 10
    check_color      = rgb($hl_check)
    fail_color       = rgb($hl_fail)
    fail_text        = <i>$FAIL ($ATTEMPTS intentos)</i>
    position         = 0, -170
    halign           = center
    valign           = center
}
