# Generado por matugen — NO EDITAR MANUALMENTE
$hl_text      = #dee3e5
$hl_fg        = #dee3e5
$hl_fg_dim    = #bfc8cb
$hl_outer     = 899295
$hl_inner     = 1b2122
$hl_font      = dee3e5
$hl_check     = 84d2e6
$hl_fail      = ffb4ab
