# Generado por matugen — NO EDITAR MANUALMENTE
$hl_text      = #e2e2e9
$hl_fg        = #e2e2e9
$hl_fg_dim    = #c4c6d0
$hl_outer     = 8e9099
$hl_inner     = 1e2025
$hl_font      = e2e2e9
$hl_check     = acc7ff
$hl_fail      = ffb4ab
