preload = /home/david/Pictures/Wallpapers/cliff-path.jpg
wallpaper = DP-2, /home/david/Pictures/Wallpapers/cliff-path.jpg
wallpaper = HDMI-A-1, /home/david/Pictures/Wallpapers/cliff-path.jpg
splash = false
