exec-once = systemctl --user start hyprpolkitagent.service
exec-once = systemctl --user start vicinae.service
exec-once = qs -p ~/.config/quickshell/mybar
exec-once = ~/.local/bin/start-hyprpaper.sh
exec-once = swaync
exec-once = nm-applet --indicator
exec-once = hypridle
exec-once = hyprctl setcursor Breeze 24
