# Generado por matugen — NO EDITAR MANUALMENTE
$primary         = rgba(90d5aeff)
$secondary       = rgba(b4ccbcff)
$tertiary        = rgba(a4cdddff)
$surface         = rgba(0f1511ff)
$outline         = rgba(8a938caa)
$outline_variant = rgba(404943aa)
