# Generado por matugen — NO EDITAR MANUALMENTE
$primary         = rgba(ffb597ff)
$secondary       = rgba(e7beaeff)
$tertiary        = rgba(d3c78fff)
$surface         = rgba(1a110eff)
$outline         = rgba(a08d86aa)
$outline_variant = rgba(53443eaa)
